[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Luxor = "ae8d54c2-7ccd-5906-9d76-62fc9837b5bc"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
